apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-sandbox
  namespace: cloud-sandbox
  labels:
    app.kubernetes.io/name: cloud-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-sandbox
  namespace: cloud-sandbox
  labels:
    app.kubernetes.io/name: cloud-sandbox
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-sandbox
  namespace: cloud-sandbox
  labels:
    app.kubernetes.io/name: cloud-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-sandbox
subjects:
- kind: ServiceAccount
  name: cloud-sandbox
  namespace: cloud-sandbox
